<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\HomeControl.Drawing.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.OidcClient.WinForms" Version="4.4.0" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Trace" Version="2.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.4.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
		<Compile Update="Views\HomeControl.Drawing.cs">
			<DependentUpon>Views\HomeControl.cs</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\MediaDisplayControl.Drawing.cs">
			<DependentUpon>Views\MediaDisplayControl.cs</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\ApplicationControl.Drawing.cs">
			<DependentUpon>Views\ApplicationControl.cs</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\AudioVolumeSlider.Drawing.cs">
			<DependentUpon>Views\AudioVolumeSlider.cs</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\MusicCardSkeleton.Drawing.cs">
			<DependentUpon>Views\MusicCardSkeleton.cs</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Properties</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Main.NativeWindow.cs">
      <DependentUpon>Main.cs</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
	  <Compile Update="Main.Drawing.cs">
		  <DependentUpon>Main.cs</DependentUpon>
		  <SubType>Code</SubType>
	  </Compile>
  </ItemGroup>

</Project>